export const CHANGE_TYPE_MENU_BUTTON = 'CHANGE_TYPE_MENU_BUTTON';
export const SCROLLING_SKILL_LIST_ITEMS = 'SCROLLING_SKILL_LIST_ITEMS';
export const ADD_SKILL_ITEM_ID = 'ADD_SKILL_ITEM_ID';
export const TRACKING_WINDOW_WIDTH = 'TRACKING_WINDOW_WIDTH';
